"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

[hyprland]
cursor_size = 20

[hyprland-start]
apptray_bluetooth=""
battery_notify=""
