"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

[hyprland-start]
apptray_bluetooth = ""
battery_notify = ""

[notification]
font_size = 6

[volume]
boost = true
boost_limit = 125
